### ISSUE TITLE
Backend folder structure refactor

### ISSUE THREAD

**Issue by mjoniec** [mjoniec/Proj2_Planes#28]
- [x] remove mock api, replace with simulated service making calls to actual api instead of real services (workers) of planes and airports 
- [x] hosted services folder: apis, background workers mqtt server, docker and compose files, separate folders and solutions
- [x] domain (plane airport - business behaviors related) - nuget - separate folder and solution
- [x] shared kernel (libs, clients (mqtt, http) contracts 
- [x] make simulated system work with traffic api on premises localhost - manual launch

**Comment by mjoniec** [comment]
- Domain object Plane should not have http client directly and handle connection logic - it should have airports data query or sth ...
-     Domain object Plane should not have stopping token, that logic belongs in host service or worker, plane should expose how to start update and stop it, business domain behavior
-     navigation (shared kernel?) class have move plane method, that is leaking language, it should have move point x by speed y on time t etc ...
-     navigation in plane or domain specific assumption (like accuracy when we consider destination as reached) should be in plane
-     plane and its navigation should be abstract to its host service, usable from simulated traffic and actual background worker 

**TODO** make a DEMO PR from this refactor, close it in one commit

**Comment by mjoniec** [comment]
Refactor folder structure with (to be confirmed with DDD guidelines)

- hosted services (apis, background workers mqtt server goes here, docker and compose files also)
- domain (plane airport - business behaviors related) - should these be nuget?
- shared kernel (libs, clients (mqtt, http) contracts
- docs
